### ISSUE TITLE
Change filter "Rolls" to "Max Roll" 

### ISSUE THREAD

**Issue by JimmyFLASH-CZE** [kfishkin/brago#1]
Current setup: "Max Roll"  filter passes if any substat has that # of rolls.
So you set it to range 3-4 and find results where are present these rolls, because you want to see them. That is fine.
But, if you set the range 0-1 or 1-1 because you want to sell them you still get the results with 2 3 or 4 rolls. That is bad!
You should change the filter to "Max Roll" and it find results where only the max roll is in selected range.
You will see what you wanted to see and for more I will see what I want.
Please! It is important! What is the biggest pain? The full stock. This will find a lot of items to sell.

**Comment by kfishkin** [comment]
added in V1.29
