### ISSUE TITLE
View some artifacts doesnt work with the preset filters anymore

### ISSUE THREAD

**Issue by Doorjam** [kfishkin/brago#3]
For example , > 2 substats, none SPD, shows no artifacts for me which is not the case in my account.

Accessory preset works though, and same with atk% gloves

https://imgur.com/a/kyBcbb4

**Comment by kfishkin** [comment]
hi, can you upload your save file so I can check?

**Comment by Doorjam** [comment]
[[](url)](https://we.tl/t-rCLQ98tGVW)

**Comment by kfishkin** [comment]
Thanks for the save file! I was able to find and fix the problem - v1.28, just pushed.

the problem was that they changed the values in the JSON save file. :(

-
